name: 'DotNetCLI'
description: 'Build, test, package, or publish a dotnet application, or run a custom dotnet command'
inputs:
  command:  # dotnet command you want to run
    description: 'The dotnet command to run. Specify 'Custom' to add arguments or use a command not listed here. Valid values are: build, push, pack, publish, restore, run, test and custom'
    required: true
    default: 'build'
  
outputs:
  result: 
    description: 'The result of the command as it would return from the commandline. A value 0 indicates success'
runs:
  using: 'node12'
  main: 'dist/index.js'
